### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by netolyrg** [Virtualstock/behave-testrail-reporter#150]
Hi, 

Thank you for this project, really useful!  

Current version in pip is 0.4.0, this release contains some bugs, for example https://github.com/Virtualstock/behave-testrail-reporter/issues/122.

Can you make new release, please? I know that I can install your package by commit hash or branch name, but it's much slower.

**Comment by BernardoSilva** [comment]
Sorry for late reply @netolyrg .
Latest release available is: https://github.com/Virtualstock/behave-testrail-reporter/releases/tag/0.5.1

Hope this helps and this package is somehow helping you. :grinning:
